# Generated by Django 4.2.5 on 2023-09-27 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_medimg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='medImg',
        ),
    ]
