# Generated by Django 4.2.5 on 2023-09-27 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0005_remove_medecin_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='image',
            field=models.ImageField(default='media/images/aaa.png', upload_to='image/'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
