# Generated by Django 4.2.5 on 2023-09-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_medecin_image_medecin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='image',
            field=models.ImageField(default='image/aaa.png', upload_to='image/'),
        ),
    ]
