# Generated by Django 4.2.5 on 2023-09-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_medecin_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='image',
            field=models.ImageField(blank=True, default='image/aaa.png', upload_to='image/'),
        ),
    ]
