# Generated by Django 4.2.5 on 2023-09-28 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_medecin_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('dr', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.medecin')),
                ('salle', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.salle')),
            ],
        ),
    ]
