# Generated by Django 4.2.5 on 2023-09-28 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_number',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_counter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.reservationcounter'),
        ),
    ]
