# Generated by Django 4.2.5 on 2023-09-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='prf',
            field=models.ImageField(blank=True, default='image/aaa.png', upload_to='media/image/'),
        ),
    ]
