# Generated by Django 4.2.5 on 2023-09-29 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_patient_prf'),
    ]

    operations = [
        migrations.CreateModel(
            name='rendezvous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=15)),
                ('prenom', models.CharField(max_length=15)),
                ('date', models.DateTimeField()),
                ('raison', models.TextField()),
                ('medecin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.medecin')),
            ],
        ),
    ]
