# Generated by Django 4.2.5 on 2023-09-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_rendezvous_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='raison',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
