# Generated by Django 4.2.5 on 2023-10-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_alter_rendezvous_raison'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='medecin',
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='medecin',
            field=models.ManyToManyField(to='pages.medecin'),
        ),
    ]
