# Generated by Django 4.2.5 on 2023-10-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_remove_rendezvous_medecin_rendezvous_medecin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='medecin',
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='medecin',
            field=models.ManyToManyField(null=True, to='pages.medecin'),
        ),
    ]
