# Generated by Django 4.2.5 on 2023-10-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_profili'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichep',
            old_name='per',
            new_name='patient',
        ),
        migrations.AddField(
            model_name='profili',
            name='nom',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profili',
            name='prenom',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profili',
            name='prf',
            field=models.ImageField(blank=True, default='image/aaa.png', upload_to='media/image/'),
        ),
        migrations.AddField(
            model_name='profili',
            name='specialite',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fichep',
            name='nom',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
