# Generated by Django 4.2.5 on 2023-10-01 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_rename_per_fichep_patient_profili_nom_profili_prenom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichep',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.patient'),
        ),
    ]
