# Generated by Django 4.2.5 on 2023-10-01 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0023_alter_fichep_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichep',
            name='desc',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='profili',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
